name: Generate PDF from README and Convert SVGs to PNGs

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Replace .drawio.svg references with .drawio.png in README.md
      run: |
        if [ -f "README.md" ]; then
          sed -i 's/\.drawio\.svg/\.drawio\.png/g' README.md
          echo "Replaced all '.drawio.svg' with '.drawio.png' in README.md"
        else
          echo "README.md not found!"
          exit 1
        fi

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex inkscape

    - name: Convert all SVGs to PNGs
      run: |
        for file in *.svg; do
          inkscape "$file" --export-filename="${file%.svg}.png"
        done

    - name: Convert README.md to PDF
      run: pandoc -o README.pdf README.md

    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: README-pdf
        path: README.pdf
